CREATE DATABASE retailsales_db;
USE retailsales_db;

CREATE TABLE orders (
    row_id INT NOT NULL,
    order_id VARCHAR(30) NOT NULL,
    order_date DATE NOT NULL,
    ship_date DATE,
    ship_mode VARCHAR(50),
    customer_id VARCHAR(20),
    customer_name VARCHAR(100),
    segment VARCHAR(50),
    country VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    region VARCHAR(50),
    product_id VARCHAR(30),
    category VARCHAR(100),
    sub_category VARCHAR(100),
    product_name VARCHAR(500),
    sales DECIMAL(12,2),
    quantity INT,
    discount DECIMAL(5,2),
    profit DECIMAL(12,2),
    PRIMARY KEY (row_id)
);

-- Insert data into tables
SHOW GLOBAL VARIABLES LIKE 'local_infile';

LOAD DATA LOCAL INFILE 'C:/Users/Administrator/Downloads/Project 1-Retail Performance Analytics/Cleaned_Retail Sales.csv'
INTO TABLE orders
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

-- 1. Database Exploration
-- Explore all objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'retailsales_db';

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'retailsales_db'
		AND TABLE_NAME ='orders';

-- 2. Dimmension Exploration
-- Explore all ship mode
SELECT DISTINCT ship_mode FROM orders;
-- We have four ship mode in total (Second Class, Standard Class, First Class, Same Day)

-- Explore all customer segments
SELECT DISTINCT segment FROM orders; 
-- We have 3 segments in total (Consumer, Corporate, Home Office)

-- Explore all regions that the orders come from
SELECT DISTINCT region, state, city FROM orders
ORDER BY 1,2,3;

SELECT COUNT(DISTINCT state), COUNT(DISTINCT city) FROM orders;
-- There are 49 states and 531 cities in the dataset.

-- Explore all categories that the company sells.
SELECT DISTINCT category, COUNT(DISTINCT sub_category) FROM orders
GROUP BY category;
-- There are 4 sub-categories in Furniture, 9 in Office Supplies and 4 in Technology.

-- 3. Date Exploration
-- Find the date of the first and the last order.
-- How many years of sales that are available.
SELECT MIN(order_date) AS first_order_date,
		MAX(order_date) AS last_order_date,
        TIMESTAMPDIFF(year, MIN(order_date), MAX(order_date))+1 AS order_range_years
FROM orders;
-- the timespan of the dataset is 4 years from 2014 to 2017.

-- 4. Measure Exploration
-- Find the total number of orders
SELECT COUNT(DISTINCT order_id) FROM orders;
-- There are 5009 orders in total.

-- Find the total number of customers that we have 
SELECT COUNT(DISTINCT customer_id) FROM orders;
-- There are 793 customers in total.

-- Find the total number of products that are sold
SELECT COUNT(distinct product_id) FROM orders;
-- There are 1862 different products that are sold.

-- Find how many items are sold
SELECT SUM(quantity) FROM orders;
-- There are 37,873 items sold in total.

-- Find the total sales
SELECT SUM(sales) FROM orders;
-- The company has the total revenue of 2,297,201.07$ generated during the period 2014-2017.

-- Find the average discount
SELECT ROUND(AVG(discount),2) FROM orders;
-- The average discount is around 16%

-- Find the total profit gained.
SELECT SUM(profit) FROM orders;
-- The total profit generated is 286,397.79$

-- Generate a report that shows all key metrics of our business.
SELECT 'Total Sales' AS measure_name, ROUND(SUM(sales),2) AS measure_value FROM orders
UNION ALL
SELECT 'Total Quantity' AS measure_name, ROUND(SUM(quantity),2) AS measure_value FROM orders
UNION ALL
SELECT 'Average Discount' AS measure_name, ROUND(AVG(discount),2) AS measure_value FROM orders
UNION ALL
SELECT 'Total Profit' AS measure_name, ROUND(SUM(profit),2) AS measure_value FROM orders
UNION ALL
SELECT 'Total Nr. order' AS measure_name, ROUND(COUNT(DISTINCT order_id),2) AS measure_value FROM orders
UNION ALL
SELECT 'Total Nr. product' AS measure_name, ROUND(COUNT(DISTINCT product_id),2) AS measure_value FROM orders
UNION ALL
SELECT 'Total Nr. customer' AS measure_name, ROUND(COUNT(DISTINCT customer_id),2) AS measure_value FROM orders;

-- 5. Magnitude Analysis
-- * SEGMENT ANALYSIS
-- What is the total revenue generated by each customer segment?
SELECT segment,
		SUM(sales) AS total_sales
FROM orders
GROUP BY segment
ORDER BY SUM(sales) DESC;
-- The Consumer generated highest total sales with $1,161,401.34, the Corporate ranked in second, then Home Office is the least.

-- What is the total profit generated by segment?
SELECT segment,
		SUM(profit) AS total_profit
FROM orders
GROUP BY segment
ORDER BY SUM(profit) DESC;
-- The consumer generated highest total profit, then corporate and the last is Home Office.

-- What is the total number of customers in each segment?
SELECT segment,
		COUNT(DISTINCT customer_id) AS total_customers
FROM orders
GROUP BY segment
ORDER BY COUNT(DISTINCT customer_id) DESC;
-- The Consumer has the highest number of customers, then the Corporate and the last is Home Office.

-- What is the average revenue per customer across each segment?
SELECT segment,
		ROUND(total_sales/total_customers,2) AS average_revenue
FROM (
SELECT segment,
		SUM(sales) AS total_sales,
        COUNT(DISTINCT customer_id) AS total_customers
FROM orders
GROUP BY segment
ORDER BY SUM(sales) DESC
) t
ORDER BY ROUND(total_sales/total_customers,2) DESC;
-- Corporate has the highest average revenue per customer, then the Home Office and last is Consumer.

-- * REGION ANALYSIS
-- What is the total number of customer across each region?
SELECT region,
	COUNT(DISTINCT customer_id) AS total_customers
FROM orders
GROUP BY region
ORDER BY COUNT(DISTINCT customer_id) DESC;
-- The West has the highest number of customers and the South has the lowest number of customers.

-- What is the total revenue generated in each region?
SELECT region,
		SUM(sales) AS total_revenue
FROM orders
GROUP BY region
ORDER BY SUM(sales) DESC; 
-- The West has the highest total revenue and the South has the lowest total revenue.

-- * CATEGORY ANALYSIS
-- What is the total number of order by each category?
SELECT category,
		COUNT(DISTINCT order_id) AS total_order
FROM orders
GROUP BY category
ORDER BY COUNT(DISTINCT order_id) DESC;
-- Office Supplies has the highest total number of orders, then is Furniture and last is Technology.

-- What is total revenue generated by each category?
SELECT category,
		SUM(sales) AS total_revenue
FROM orders
GROUP BY category
ORDER BY SUM(sales) DESC;
-- The Technology generated the highest total revenue and Office Supplies generated the lowest total revenue.
-- Insight: This means that Technology is the high-value category and Office Supplies is the lowest value category.

-- What is total profit by each category?
SELECT category,
		SUM(profit) AS total_profit
FROM orders
GROUP BY category
ORDER BY SUM(profit) DESC;
-- Technology generated the highest profit while Furniture generated relatively low profit. This means there are underlying factor that reduce the total profit of Furniture.

-- What is the average discount by each category?
SELECT category,
		ROUND(AVG(discount)*100,2) AS average_discount
FROM orders
GROUP BY category
ORDER BY AVG(discount) DESC;
-- The result shows that Furniture has the highest average discount rate (17.39%) and Technology has the lowest discount rate (13.23%)
-- Insights: The high-discount policy on the Furniture category is one of the main reasons that cause low-profit in this category.

-- 6. Ranking Analysis
-- Find the top 10 customers who have generated the highest revenue
SELECT customer_id,
		customer_name,
        SUM(sales) AS total_sales
FROM orders
GROUP BY customer_id,
			customer_name
ORDER BY SUM(sales) DESC
LIMIT 10;

-- Which are top 5 highest-profit states?
SELECT state,
		SUM(profit) AS total_profit
FROM orders
GROUP BY state
ORDER BY SUM(profit) DESC
LIMIT 5;
-- California and New York are the top 2 highest-profit states
SELECT state,
		SUM(profit) AS total_profit
FROM orders
GROUP BY state
ORDER BY SUM(profit)
LIMIT 5;
-- Texas and Ohio are the top 2 lowest-profit states

-- Which are top 10 best-performing sub-categories in terms of profit?
SELECT sub_category,
        SUM(profit) AS total_profit
FROM orders
GROUP BY sub_category
ORDER BY SUM(profit) DESC
LIMIT 10;
-- Copiers and Phones are the 2 highest-profit sub-categories with 55,617.90$ and 44,516.25$ respectively.

-- Find the top 10 worst-performing categories in terms of profit?
SELECT sub_category,
        SUM(profit) AS total_revenue
FROM orders
GROUP BY sub_category
ORDER BY SUM(profit)
LIMIT 10;
-- The 2 lowest-performing sub-categories are tables and bookcases with -17,725.59$ and -3,472.56$

-- Create a purchase_frequency table
CREATE VIEW purchase_frequency AS
WITH purchase_frequency_tb AS (
    SELECT 
        customer_id,
        segment,
        CASE 
            WHEN COUNT(DISTINCT order_id) BETWEEN 1 AND 4 THEN '1-4'
            WHEN COUNT(DISTINCT order_id) BETWEEN 5 AND 9 THEN '5-9'
            ELSE '>=10'
        END AS purchase_frequency
    FROM orders
    GROUP BY 
        customer_id,
        segment
)
SELECT 
    purchase_frequency,
    segment,
    COUNT(DISTINCT customer_id) AS total_num_customers
FROM purchase_frequency_tb
GROUP BY 
    purchase_frequency,
    segment
ORDER BY 
    purchase_frequency,
    segment;


-- Create a customer_revenue table
SELECT total_customers,
		total_customers * 0.1 AS Top10percentage
FROM (
SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM orders
) t;
-- Top 10% customers is 80 customers with the highest revenue
CREATE VIEW customer_revenue AS
WITH customer_revenue AS(
SELECT customer_id,
		segment,
		SUM(sales) AS total_sales
FROM orders
GROUP BY customer_id,
		segment
ORDER BY segment
)
, running_total_revenue AS(
SELECT customer_id,
		segment,
        total_sales,
        SUM(total_sales) OVER(ORDER BY total_sales DESC) AS running_total_sales
FROM customer_revenue
)
SELECT customer_id,
		segment,
        total_sales,
        running_total_sales,
        running_total_sales/ SUM(total_sales) OVER() AS sales_percentage
FROM running_total_revenue
LIMIT 80;
